import { Client, Maintenance, Message, DashboardStats } from "./types";

export const clienti: Client[] = [
  {
    id: "c1",
    nume: "Ion Popescu",
    telefon: "0722 111 222",
    email: "ion.popescu@email.ro",
    adresa: "Str. Libertatii 45, Ap. 12",
    oras: "Bucuresti",
    status: "activ",
    dataContract: "2024-03-15",
    tipFiltru: "osmoza_inversa",
    ultimaMentenanta: "2026-01-10",
    urmatoareaMentenanta: "2026-04-10",
    notite: "Filtru instalat in bucatarie. Acces prin usa din spate.",
  },
  {
    id: "c2",
    nume: "Maria Ionescu",
    telefon: "0733 222 333",
    email: "maria.ionescu@email.ro",
    adresa: "Bd. Unirii 120, Et. 3",
    oras: "Bucuresti",
    status: "activ",
    dataContract: "2024-06-01",
    tipFiltru: "carbon_activ",
    ultimaMentenanta: "2026-02-20",
    urmatoareaMentenanta: "2026-05-20",
    notite: "Preferate programari dupa ora 17:00.",
  },
  {
    id: "c3",
    nume: "Andrei Dumitrescu",
    telefon: "0744 333 444",
    email: "andrei.d@email.ro",
    adresa: "Str. Florilor 8",
    oras: "Cluj-Napoca",
    status: "activ",
    dataContract: "2025-01-10",
    tipFiltru: "ultrafiltrare",
    ultimaMentenanta: "2026-03-05",
    urmatoareaMentenanta: "2026-06-05",
    notite: "Sistem industrial. Necesita 2 tehnicieni.",
  },
  {
    id: "c4",
    nume: "Elena Stanescu",
    telefon: "0755 444 555",
    email: "elena.s@email.ro",
    adresa: "Str. Mihai Viteazu 22",
    oras: "Timisoara",
    status: "nou",
    dataContract: "2026-03-28",
    tipFiltru: "sediment",
    ultimaMentenanta: "-",
    urmatoareaMentenanta: "2026-04-15",
    notite: "Client nou. Prima instalare programata.",
  },
  {
    id: "c5",
    nume: "George Marin",
    telefon: "0766 555 666",
    email: "george.marin@email.ro",
    adresa: "Calea Victoriei 88",
    oras: "Bucuresti",
    status: "activ",
    dataContract: "2023-11-20",
    tipFiltru: "osmoza_inversa",
    ultimaMentenanta: "2025-12-15",
    urmatoareaMentenanta: "2026-03-15",
    notite: "Mentenanta restanta! De contactat urgent.",
  },
  {
    id: "c6",
    nume: "Ana Petrescu",
    telefon: "0777 666 777",
    email: "ana.p@email.ro",
    adresa: "Str. Aviatorilor 15",
    oras: "Iasi",
    status: "activ",
    dataContract: "2024-09-12",
    tipFiltru: "carbon_activ",
    ultimaMentenanta: "2026-03-01",
    urmatoareaMentenanta: "2026-06-01",
    notite: "",
  },
  {
    id: "c7",
    nume: "Mihai Constantinescu",
    telefon: "0788 777 888",
    email: "mihai.c@email.ro",
    adresa: "Bd. Decebal 33",
    oras: "Constanta",
    status: "inactiv",
    dataContract: "2023-05-01",
    tipFiltru: "sediment",
    ultimaMentenanta: "2025-05-01",
    urmatoareaMentenanta: "-",
    notite: "Contract expirat. De contactat pentru reinoire.",
  },
  {
    id: "c8",
    nume: "Cristina Voicu",
    telefon: "0799 888 999",
    email: "cristina.v@email.ro",
    adresa: "Str. Primaverii 7, Ap. 4",
    oras: "Brasov",
    status: "activ",
    dataContract: "2025-02-14",
    tipFiltru: "ultrafiltrare",
    ultimaMentenanta: "2026-02-14",
    urmatoareaMentenanta: "2026-05-14",
    notite: "Apartament la etajul 4. Interfon: 4.",
  },
  {
    id: "c9",
    nume: "Restaurant La Bucatar",
    telefon: "0721 999 000",
    email: "contact@labucatar.ro",
    adresa: "Str. Gabroveni 12",
    oras: "Bucuresti",
    status: "activ",
    dataContract: "2024-01-15",
    tipFiltru: "osmoza_inversa",
    ultimaMentenanta: "2026-03-20",
    urmatoareaMentenanta: "2026-04-20",
    notite: "Client business. Mentenanta lunara. Contact: Chef Radu.",
  },
  {
    id: "c10",
    nume: "Florin Neagu",
    telefon: "0732 000 111",
    email: "florin.n@email.ro",
    adresa: "Str. Lalelelor 55",
    oras: "Sibiu",
    status: "nou",
    dataContract: "2026-04-01",
    tipFiltru: "carbon_activ",
    ultimaMentenanta: "-",
    urmatoareaMentenanta: "2026-04-08",
    notite: "Client nou. Referral de la Ion Popescu.",
  },
];

export const mentenante: Maintenance[] = [
  {
    id: "m1",
    clientId: "c1",
    clientNume: "Ion Popescu",
    data: "2026-04-10",
    ora: "09:00",
    tip: "schimb_filtru",
    status: "programat",
    tehnician: "Alexandru Badea",
    notite: "Schimb filtru osmoza inversa - set complet",
    durata: 60,
  },
  {
    id: "m2",
    clientId: "c4",
    clientNume: "Elena Stanescu",
    data: "2026-04-15",
    ora: "10:00",
    tip: "instalare",
    status: "programat",
    tehnician: "Bogdan Cristea",
    notite: "Prima instalare filtru sediment",
    durata: 120,
  },
  {
    id: "m3",
    clientId: "c5",
    clientNume: "George Marin",
    data: "2026-04-04",
    ora: "14:00",
    tip: "schimb_filtru",
    status: "in_lucru",
    tehnician: "Alexandru Badea",
    notite: "Mentenanta restanta - prioritar",
    durata: 60,
  },
  {
    id: "m4",
    clientId: "c9",
    clientNume: "Restaurant La Bucatar",
    data: "2026-04-20",
    ora: "08:00",
    tip: "verificare",
    status: "programat",
    tehnician: "Bogdan Cristea",
    notite: "Verificare lunara sistem osmoza",
    durata: 45,
  },
  {
    id: "m5",
    clientId: "c10",
    clientNume: "Florin Neagu",
    data: "2026-04-08",
    ora: "11:00",
    tip: "instalare",
    status: "programat",
    tehnician: "Alexandru Badea",
    notite: "Instalare filtru carbon activ",
    durata: 90,
  },
  {
    id: "m6",
    clientId: "c3",
    clientNume: "Andrei Dumitrescu",
    data: "2026-04-04",
    ora: "09:00",
    tip: "verificare",
    status: "finalizat",
    tehnician: "Bogdan Cristea",
    notite: "Verificare sistem ultrafiltrare - totul OK",
    durata: 60,
  },
  {
    id: "m7",
    clientId: "c2",
    clientNume: "Maria Ionescu",
    data: "2026-04-03",
    ora: "17:30",
    tip: "schimb_filtru",
    status: "finalizat",
    tehnician: "Alexandru Badea",
    notite: "Schimb filtru carbon activ",
    durata: 45,
  },
  {
    id: "m8",
    clientId: "c6",
    clientNume: "Ana Petrescu",
    data: "2026-04-06",
    ora: "10:00",
    tip: "reparatie",
    status: "programat",
    tehnician: "Bogdan Cristea",
    notite: "Pierdere apa la imbinare - de verificat",
    durata: 60,
  },
];

export const mesaje: Message[] = [
  {
    id: "msg1",
    clientId: "c1",
    clientNume: "Ion Popescu",
    telefon: "0722 111 222",
    continut:
      "Buna ziua, va reamintim ca aveti programata mentenanta filtrului de apa pe data de 10 aprilie, ora 09:00. Va rugam sa confirmati disponibilitatea.",
    dataTrimitere: "2026-04-03",
    status: "citit",
    tip: "reminder",
  },
  {
    id: "msg2",
    clientId: "c4",
    clientNume: "Elena Stanescu",
    telefon: "0755 444 555",
    continut:
      "Buna ziua! Bine ati venit la AquaService. Instalarea filtrului dvs. este programata pe 15 aprilie, ora 10:00. Tehnicianul nostru va va contacta cu 30 min inainte.",
    dataTrimitere: "2026-04-02",
    status: "livrat",
    tip: "confirmare",
  },
  {
    id: "msg3",
    clientId: "c5",
    clientNume: "George Marin",
    telefon: "0766 555 666",
    continut:
      "Buna ziua, mentenanta filtrului dvs. este restanta. Va rugam sa ne contactati la 0800 123 456 pentru a programa o vizita cat mai curand.",
    dataTrimitere: "2026-04-01",
    status: "citit",
    tip: "reminder",
  },
  {
    id: "msg4",
    clientId: "c9",
    clientNume: "Restaurant La Bucatar",
    telefon: "0721 999 000",
    continut:
      "Verificarea lunara a sistemului de filtrare este programata pe 20 aprilie, ora 08:00. Va rugam sa asigurati accesul tehnicianului.",
    dataTrimitere: "2026-04-03",
    status: "trimis",
    tip: "reminder",
  },
  {
    id: "msg5",
    clientId: "c7",
    clientNume: "Mihai Constantinescu",
    telefon: "0788 777 888",
    continut:
      "Buna ziua, contractul dvs. de mentenanta a expirat. Dorim sa va oferim o oferta speciala pentru reinoire. Sunati-ne la 0800 123 456.",
    dataTrimitere: "2026-03-28",
    status: "esuat",
    tip: "urmarire",
  },
  {
    id: "msg6",
    clientId: "c10",
    clientNume: "Florin Neagu",
    telefon: "0732 000 111",
    continut:
      "Buna ziua! Va confirmare instalarea filtrului pe data de 8 aprilie, ora 11:00. Tehnicianul Alexandru va sosi cu toate materialele necesare.",
    dataTrimitere: "2026-04-03",
    status: "livrat",
    tip: "confirmare",
  },
];

export const dashboardStats: DashboardStats = {
  totalClienti: 10,
  mentenanteLuna: 8,
  programariAzi: 2,
  mesajeTrimise: 6,
  clientiNoi: 2,
  mentenanteRestante: 1,
};

export const tehnicieni = ["Alexandru Badea", "Bogdan Cristea"];

export const filterTypeLabels: Record<string, string> = {
  osmoza_inversa: "Osmoza Inversa",
  carbon_activ: "Carbon Activ",
  sediment: "Sediment",
  ultrafiltrare: "Ultrafiltrare",
};

export const maintenanceTypeLabels: Record<string, string> = {
  schimb_filtru: "Schimb Filtru",
  verificare: "Verificare",
  instalare: "Instalare",
  reparatie: "Reparatie",
};

export const statusLabels: Record<string, string> = {
  activ: "Activ",
  inactiv: "Inactiv",
  nou: "Nou",
  programat: "Programat",
  in_lucru: "In Lucru",
  finalizat: "Finalizat",
  anulat: "Anulat",
  trimis: "Trimis",
  livrat: "Livrat",
  citit: "Citit",
  esuat: "Esuat",
};
